version: '3.6'
services:
  php:
    build: .docker/php
    ports:
      - 8080:80
    volumes:
      - ./src/:/var/www/html/
      - ./.docker/apache/default.conf/:/etc/apache2/sites-enabled/000-default.conf
    env_file:
      - ./src/.env
    networks:
      - app

  database:
    image: mysql:5.5
    ports:
      - 3306:3306
    volumes:
      - esgi_collab_volume:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=default
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - app

volumes:
  esgi_collab_volume:

networks:
  app:
    driver: bridge